name: 2020-07-22-mag-search
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake-minimal=5.20.1
  - pandas=1.0.5
  - ipython=7.16.1
  - jupyterlab=2.2.0
  - xlrd=1.2.0
  - ipywidgets=7.5.1
  - nodejs=14.6.0
